#!/bin/sh
# make-macaron-icon.sh — build the Macaros app-icon assets from the source image.
#
# Input : Macaros-source.png  (the raw AI-generated macaron, opaque white background)
# Output: (written next to this script, in hosted/cocoametal/)
#   Macaros-1024.png   macOS-spec master (transparent squircle)
#   Macaros.icns       multi-resolution icon for the .app (CFBundleIconFile)
#   macaron_icon.h     the 256px master as base64, embedded in the dylib and decoded
#                      by cmsh_make_icon() so bare/headless runs get the icon too
#
# macOS 11+ (Big Sur) app-icon grid — baked into the art because, unlike iOS, macOS does
# NOT auto-mask app icons. Get this wrong and the tile renders oversized and overflows the
# Dock selection box:
#   canvas 1024x1024 · tile (rounded body) 824x824 (80.5%) · 100px margin each side ·
#   corner radius 185.4px (= 0.225 x 824), continuous/squircle corners (we approximate
#   with a circular arc — indistinguishable at Dock sizes).
#   Refs: Apple HIG "App icons"; Apple Developer Forums thread 670578.
#
# Two ImageMagick traps this script works around (both cost real time to rediscover):
#   - a Gray-colorspace mask silently collapses the DstIn result to grayscale and drops
#     the macaron's colour -> force the mask to sRGB first.
#   - chaining -extent after -composite drops the pixels -> pad in a separate magick call.
#
# Requires: ImageMagick (magick), iconutil (macOS), base64. After running, rebuild the
# dylib so the new embed ships:  make cocoametal-dylib
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="${1:-$HERE/Macaros-source.png}"
[ -f "$SRC" ] || { echo "source image not found: $SRC (pass one as \$1)" >&2; exit 1; }
command -v magick   >/dev/null 2>&1 || { echo "need ImageMagick (magick)" >&2; exit 1; }
command -v iconutil >/dev/null 2>&1 || { echo "need iconutil (macOS)" >&2; exit 1; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
T=824; SS=4; RSS=741.6            # tile side, supersample, radius*SS (185.4 * 4)

# 1. White background -> transparent. A connected flood-fill from the four corners removes
#    only the outer white, preserving the near-white top-left highlight that a global
#    "-transparent white" would eat; then shave a 2px anti-alias halo.
W="$(magick identify -format '%w' "$SRC")"; H="$(magick identify -format '%h' "$SRC")"
magick "$SRC" -alpha set -fill none -fuzz 9% \
  -floodfill +0+0 white -floodfill "+$((W-1))+0" white \
  -floodfill "+0+$((H-1))" white -floodfill "+$((W-1))+$((H-1))" white \
  -channel A -morphology Erode Disk:2 +channel \
  "$TMP/masked.png"

# 2. Trim the transparent frame, scale the squircle art to the 824 tile.
magick "$TMP/masked.png" -trim +repage -resize "${T}x${T}" "$TMP/art.png"

# 3. Anti-aliased circular rounded-rect mask at radius 185.4 (drawn 4x, downsampled).
magick -size "$((T*SS))x$((T*SS))" xc:none -fill white \
  -draw "roundRectangle 0,0 $((T*SS-1)),$((T*SS-1)) $RSS,$RSS" \
  -filter Lanczos -resize "${T}x${T}" "$TMP/mask.png"

# 4. Clip the art to the tile (mask forced to sRGB — see header note).
magick "$TMP/art.png" \( "$TMP/mask.png" -colorspace sRGB \) \
  -compose DstIn -composite "$TMP/tile.png"

# 5. Centre the tile on a 1024 canvas with 100px transparent margins (separate call).
magick "$TMP/tile.png" -background none -gravity center -extent 1024x1024 \
  "$HERE/Macaros-1024.png"

# 6. .icns — every size derived from the 1024 master.
IS="$TMP/Macaros.iconset"; mkdir -p "$IS"
for pair in "16 16x16" "32 16x16@2x" "32 32x32" "64 32x32@2x" "128 128x128" \
            "256 128x128@2x" "256 256x256" "512 256x256@2x" "512 512x512" "1024 512x512@2x"; do
  set -- $pair
  magick "$HERE/Macaros-1024.png" -resize "${1}x${1}" -filter Lanczos "$IS/icon_${2}.png"
done
iconutil -c icns "$IS" -o "$HERE/Macaros.icns"

# 7. 256px master -> base64 -> macaron_icon.h (embedded in the dylib).
magick "$HERE/Macaros-1024.png" -resize 256x256 "$TMP/m256.png"
{
  printf '%s\n' \
'/* macaron_icon.h -- GENERATED by make-macaron-icon.sh, do not hand-edit.' \
' *' \
' * The app icon: a 256px macOS-spec macaron tile (824/1024 body, 100px margin,' \
' * 185.4px corner radius) as base64, decoded by cmsh_make_icon() so the dylib sets' \
' * the Dock/menu icon with no external file (bare aros-ctl/run-window + headless too).' \
' * Regenerate: ./hosted/cocoametal/make-macaron-icon.sh  (then: make cocoametal-dylib)' \
' */'
  printf 'static const char macaron_icon_b64[] =\n'
  base64 -i "$TMP/m256.png" | tr -d '\n' | fold -w 76 | sed 's/^/"/; s/$/"/'
  printf ';\n'
} > "$HERE/macaron_icon.h"

echo ">> wrote Macaros-1024.png, Macaros.icns, macaron_icon.h in $HERE"
echo ">> master: $(magick "$HERE/Macaros-1024.png" -format '%@ on %wx%h' info:)  (expect 824x824+100+100 on 1024x1024)"
echo ">> now rebuild the dylib to ship the new embed:  make cocoametal-dylib"
