/* GENERATED by graft/gen-struct-layouts - do not edit.
 *
 * m68k (AmigaOS ABI) offsets of the structures the 68k execution
 * service fills in on the guest's behalf. Derived from the AROS
 * headers with a 2-byte-packed m68k probe and locked by the
 * generator's KNOWN_M68K self-check. */
#ifndef EMU68K_GUEST_OFFSETS_H
#define EMU68K_GUEST_OFFSETS_H

/* struct Task: 92 bytes on m68k (Task) */
#define M68K_Task_SIZEOF 92
#define M68K_Task_tc_Node_ln_Succ 0
#define M68K_Task_tc_Node_ln_Pred 4
#define M68K_Task_tc_Node_ln_Type 8
#define M68K_Task_tc_Node_ln_Pri 9
#define M68K_Task_tc_Node_ln_Name 10
#define M68K_Task_tc_Flags 14
#define M68K_Task_tc_State 15
#define M68K_Task_tc_IDNestCnt 16
#define M68K_Task_tc_TDNestCnt 17
#define M68K_Task_tc_SigAlloc 18
#define M68K_Task_tc_SigWait 22
#define M68K_Task_tc_SigRecvd 26
#define M68K_Task_tc_SigExcept 30
#define M68K_Task_tc_UnionETask_tc_ETrap_tc_ETrapAlloc 34
#define M68K_Task_tc_UnionETask_tc_ETrap_tc_ETrapAble 36
#define M68K_Task_tc_ExceptData 38
#define M68K_Task_tc_ExceptCode 42
#define M68K_Task_tc_TrapData 46
#define M68K_Task_tc_TrapCode 50
#define M68K_Task_tc_SPReg 54
#define M68K_Task_tc_SPLower 58
#define M68K_Task_tc_SPUpper 62
#define M68K_Task_tc_Switch 66
#define M68K_Task_tc_Launch 70
#define M68K_Task_tc_MemEntry_lh_Head 74
#define M68K_Task_tc_MemEntry_lh_Tail 78
#define M68K_Task_tc_MemEntry_lh_TailPred 82
#define M68K_Task_tc_MemEntry_lh_Type 86
#define M68K_Task_tc_MemEntry_l_pad 87
#define M68K_Task_tc_UserData 88

/* struct ExecBase: 640 bytes on m68k (ExecBase) */
#define M68K_ExecBase_SIZEOF 640
#define M68K_ExecBase_LibNode_lib_Node_ln_Succ 0
#define M68K_ExecBase_LibNode_lib_Node_ln_Pred 4
#define M68K_ExecBase_LibNode_lib_Node_ln_Type 8
#define M68K_ExecBase_LibNode_lib_Node_ln_Pri 9
#define M68K_ExecBase_LibNode_lib_Node_ln_Name 10
#define M68K_ExecBase_LibNode_lib_Flags 14
#define M68K_ExecBase_LibNode_lib_pad 15
#define M68K_ExecBase_LibNode_lib_NegSize 16
#define M68K_ExecBase_LibNode_lib_PosSize 18
#define M68K_ExecBase_LibNode_lib_Version 20
#define M68K_ExecBase_LibNode_lib_Revision 22
#define M68K_ExecBase_LibNode_lib_IdString 24
#define M68K_ExecBase_LibNode_lib_Sum 28
#define M68K_ExecBase_LibNode_lib_OpenCnt 32
#define M68K_ExecBase_SoftVer 34
#define M68K_ExecBase_LowMemChkSum 36
#define M68K_ExecBase_ChkBase 38
#define M68K_ExecBase_ColdCapture 42
#define M68K_ExecBase_CoolCapture 46
#define M68K_ExecBase_WarmCapture 50
#define M68K_ExecBase_SysStkUpper 54
#define M68K_ExecBase_SysStkLower 58
#define M68K_ExecBase_MaxLocMem 62
#define M68K_ExecBase_DebugEntry 66
#define M68K_ExecBase_DebugData 70
#define M68K_ExecBase_AlertData 74
#define M68K_ExecBase_MaxExtMem 78
#define M68K_ExecBase_ChkSum 82
#define M68K_ExecBase_IntVects 84
#define M68K_ExecBase_ThisTask 276
#define M68K_ExecBase_IdleCount 280
#define M68K_ExecBase_DispCount 284
#define M68K_ExecBase_Quantum 288
#define M68K_ExecBase_Elapsed 290
#define M68K_ExecBase_SysFlags 292
#define M68K_ExecBase_IDNestCnt 294
#define M68K_ExecBase_TDNestCnt 295
#define M68K_ExecBase_AttnFlags 296
#define M68K_ExecBase_AttnResched 298
#define M68K_ExecBase_ResModules 300
#define M68K_ExecBase_TaskTrapCode 304
#define M68K_ExecBase_TaskExceptCode 308
#define M68K_ExecBase_TaskExitCode 312
#define M68K_ExecBase_TaskSigAlloc 316
#define M68K_ExecBase_TaskTrapAlloc 320
#define M68K_ExecBase_MemList_lh_Head 322
#define M68K_ExecBase_MemList_lh_Tail 326
#define M68K_ExecBase_MemList_lh_TailPred 330
#define M68K_ExecBase_MemList_lh_Type 334
#define M68K_ExecBase_MemList_l_pad 335
#define M68K_ExecBase_ResourceList_lh_Head 336
#define M68K_ExecBase_ResourceList_lh_Tail 340
#define M68K_ExecBase_ResourceList_lh_TailPred 344
#define M68K_ExecBase_ResourceList_lh_Type 348
#define M68K_ExecBase_ResourceList_l_pad 349
#define M68K_ExecBase_DeviceList_lh_Head 350
#define M68K_ExecBase_DeviceList_lh_Tail 354
#define M68K_ExecBase_DeviceList_lh_TailPred 358
#define M68K_ExecBase_DeviceList_lh_Type 362
#define M68K_ExecBase_DeviceList_l_pad 363
#define M68K_ExecBase_IntrList_lh_Head 364
#define M68K_ExecBase_IntrList_lh_Tail 368
#define M68K_ExecBase_IntrList_lh_TailPred 372
#define M68K_ExecBase_IntrList_lh_Type 376
#define M68K_ExecBase_IntrList_l_pad 377
#define M68K_ExecBase_LibList_lh_Head 378
#define M68K_ExecBase_LibList_lh_Tail 382
#define M68K_ExecBase_LibList_lh_TailPred 386
#define M68K_ExecBase_LibList_lh_Type 390
#define M68K_ExecBase_LibList_l_pad 391
#define M68K_ExecBase_PortList_lh_Head 392
#define M68K_ExecBase_PortList_lh_Tail 396
#define M68K_ExecBase_PortList_lh_TailPred 400
#define M68K_ExecBase_PortList_lh_Type 404
#define M68K_ExecBase_PortList_l_pad 405
#define M68K_ExecBase_TaskReady_lh_Head 406
#define M68K_ExecBase_TaskReady_lh_Tail 410
#define M68K_ExecBase_TaskReady_lh_TailPred 414
#define M68K_ExecBase_TaskReady_lh_Type 418
#define M68K_ExecBase_TaskReady_l_pad 419
#define M68K_ExecBase_TaskWait_lh_Head 420
#define M68K_ExecBase_TaskWait_lh_Tail 424
#define M68K_ExecBase_TaskWait_lh_TailPred 428
#define M68K_ExecBase_TaskWait_lh_Type 432
#define M68K_ExecBase_TaskWait_l_pad 433
#define M68K_ExecBase_SoftInts 434
#define M68K_ExecBase_LastAlert 514
#define M68K_ExecBase_VBlankFrequency 530
#define M68K_ExecBase_PowerSupplyFrequency 531
#define M68K_ExecBase_SemaphoreList_lh_Head 532
#define M68K_ExecBase_SemaphoreList_lh_Tail 536
#define M68K_ExecBase_SemaphoreList_lh_TailPred 540
#define M68K_ExecBase_SemaphoreList_lh_Type 544
#define M68K_ExecBase_SemaphoreList_l_pad 545
#define M68K_ExecBase_KickMemPtr 546
#define M68K_ExecBase_KickTagPtr 550
#define M68K_ExecBase_KickCheckSum 554
#define M68K_ExecBase_ex_Pad0 558
#define M68K_ExecBase_ex_LaunchPoint 560
#define M68K_ExecBase_ex_RamLibPrivate 564
#define M68K_ExecBase_ex_EClockFrequency 568
#define M68K_ExecBase_ex_CacheControl 572
#define M68K_ExecBase_ex_TaskID 576
#define M68K_ExecBase_ex_Reserved1 580
#define M68K_ExecBase_ex_MMULock 600
#define M68K_ExecBase_ex_Reserved2 604
#define M68K_ExecBase_ex_DebugFlags 612
#define M68K_ExecBase_ex_MemHandlers_mlh_Head 616
#define M68K_ExecBase_ex_MemHandlers_mlh_Tail 620
#define M68K_ExecBase_ex_MemHandlers_mlh_TailPred 624
#define M68K_ExecBase_ex_MemHandler 628
#define M68K_ExecBase_DebugAROSBase 632
#define M68K_ExecBase_lb_TaskResBase 636

/* struct Library: 34 bytes on m68k (Library) */
#define M68K_Library_SIZEOF 34
#define M68K_Library_lib_Node_ln_Succ 0
#define M68K_Library_lib_Node_ln_Pred 4
#define M68K_Library_lib_Node_ln_Type 8
#define M68K_Library_lib_Node_ln_Pri 9
#define M68K_Library_lib_Node_ln_Name 10
#define M68K_Library_lib_Flags 14
#define M68K_Library_lib_pad 15
#define M68K_Library_lib_NegSize 16
#define M68K_Library_lib_PosSize 18
#define M68K_Library_lib_Version 20
#define M68K_Library_lib_Revision 22
#define M68K_Library_lib_IdString 24
#define M68K_Library_lib_Sum 28
#define M68K_Library_lib_OpenCnt 32

/* struct CommandLineInterface: 68 bytes on m68k (CommandLineInterface) */
#define M68K_CommandLineInterface_SIZEOF 68
#define M68K_CommandLineInterface_cli_Result2 0
#define M68K_CommandLineInterface_cli_SetName 4
#define M68K_CommandLineInterface_cli_CommandDir 8
#define M68K_CommandLineInterface_cli_ReturnCode 12
#define M68K_CommandLineInterface_cli_CommandName 16
#define M68K_CommandLineInterface_cli_FailLevel 20
#define M68K_CommandLineInterface_cli_Prompt 24
#define M68K_CommandLineInterface_cli_StandardInput 28
#define M68K_CommandLineInterface_cli_CurrentInput 32
#define M68K_CommandLineInterface_cli_CommandFile 36
#define M68K_CommandLineInterface_cli_Interactive 40
#define M68K_CommandLineInterface_cli_Background 44
#define M68K_CommandLineInterface_cli_CurrentOutput 48
#define M68K_CommandLineInterface_cli_DefaultStack 52
#define M68K_CommandLineInterface_cli_StandardOutput 56
#define M68K_CommandLineInterface_cli_Module 60
#define M68K_CommandLineInterface_cli_StandardError 64

/* struct MsgPort: 42 bytes on m68k (MsgPort) */
#define M68K_MsgPort_SIZEOF 42
#define M68K_MsgPort_mp_Node_ln_Succ 0
#define M68K_MsgPort_mp_Node_ln_Pred 4
#define M68K_MsgPort_mp_Node_ln_Type 8
#define M68K_MsgPort_mp_Node_ln_Pri 9
#define M68K_MsgPort_mp_Node_ln_Name 10
#define M68K_MsgPort_mp_Flags 14
#define M68K_MsgPort_mp_SigBit 15
#define M68K_MsgPort_mp_SigTask 16
#define M68K_MsgPort_mp_MsgList_lh_Head 20
#define M68K_MsgPort_mp_MsgList_lh_Tail 24
#define M68K_MsgPort_mp_MsgList_lh_TailPred 28
#define M68K_MsgPort_mp_MsgList_lh_Type 32
#define M68K_MsgPort_mp_MsgList_l_pad 33
#define M68K_MsgPort_mp_Pad_slock 34
#define M68K_MsgPort_mp_Pad_s_Owner 38

/* struct Message: 20 bytes on m68k (Message) */
#define M68K_Message_SIZEOF 20
#define M68K_Message_mn_Node_ln_Succ 0
#define M68K_Message_mn_Node_ln_Pred 4
#define M68K_Message_mn_Node_ln_Type 8
#define M68K_Message_mn_Node_ln_Pri 9
#define M68K_Message_mn_Node_ln_Name 10
#define M68K_Message_mn_ReplyPort 14
#define M68K_Message_mn_Length 18

/* struct List: 14 bytes on m68k (List) */
#define M68K_List_SIZEOF 14
#define M68K_List_lh_Head 0
#define M68K_List_lh_Tail 4
#define M68K_List_lh_TailPred 8
#define M68K_List_lh_Type 12
#define M68K_List_l_pad 13

/* struct Node: 14 bytes on m68k (Node) */
#define M68K_Node_SIZEOF 14
#define M68K_Node_ln_Succ 0
#define M68K_Node_ln_Pred 4
#define M68K_Node_ln_Type 8
#define M68K_Node_ln_Pri 9
#define M68K_Node_ln_Name 10

/* struct Process: 236 bytes on m68k (Process) */
#define M68K_Process_SIZEOF 236
#define M68K_Process_pr_Task_tc_Node_ln_Succ 0
#define M68K_Process_pr_Task_tc_Node_ln_Pred 4
#define M68K_Process_pr_Task_tc_Node_ln_Type 8
#define M68K_Process_pr_Task_tc_Node_ln_Pri 9
#define M68K_Process_pr_Task_tc_Node_ln_Name 10
#define M68K_Process_pr_Task_tc_Flags 14
#define M68K_Process_pr_Task_tc_State 15
#define M68K_Process_pr_Task_tc_IDNestCnt 16
#define M68K_Process_pr_Task_tc_TDNestCnt 17
#define M68K_Process_pr_Task_tc_SigAlloc 18
#define M68K_Process_pr_Task_tc_SigWait 22
#define M68K_Process_pr_Task_tc_SigRecvd 26
#define M68K_Process_pr_Task_tc_SigExcept 30
#define M68K_Process_pr_Task_tc_UnionETask_tc_ETrap_tc_ETrapAlloc 34
#define M68K_Process_pr_Task_tc_UnionETask_tc_ETrap_tc_ETrapAble 36
#define M68K_Process_pr_Task_tc_ExceptData 38
#define M68K_Process_pr_Task_tc_ExceptCode 42
#define M68K_Process_pr_Task_tc_TrapData 46
#define M68K_Process_pr_Task_tc_TrapCode 50
#define M68K_Process_pr_Task_tc_SPReg 54
#define M68K_Process_pr_Task_tc_SPLower 58
#define M68K_Process_pr_Task_tc_SPUpper 62
#define M68K_Process_pr_Task_tc_Switch 66
#define M68K_Process_pr_Task_tc_Launch 70
#define M68K_Process_pr_Task_tc_MemEntry_lh_Head 74
#define M68K_Process_pr_Task_tc_MemEntry_lh_Tail 78
#define M68K_Process_pr_Task_tc_MemEntry_lh_TailPred 82
#define M68K_Process_pr_Task_tc_MemEntry_lh_Type 86
#define M68K_Process_pr_Task_tc_MemEntry_l_pad 87
#define M68K_Process_pr_Task_tc_UserData 88
#define M68K_Process_pr_MsgPort_mp_Node_ln_Succ 92
#define M68K_Process_pr_MsgPort_mp_Node_ln_Pred 96
#define M68K_Process_pr_MsgPort_mp_Node_ln_Type 100
#define M68K_Process_pr_MsgPort_mp_Node_ln_Pri 101
#define M68K_Process_pr_MsgPort_mp_Node_ln_Name 102
#define M68K_Process_pr_MsgPort_mp_Flags 106
#define M68K_Process_pr_MsgPort_mp_SigBit 107
#define M68K_Process_pr_MsgPort_mp_SigTask 108
#define M68K_Process_pr_MsgPort_mp_MsgList_lh_Head 112
#define M68K_Process_pr_MsgPort_mp_MsgList_lh_Tail 116
#define M68K_Process_pr_MsgPort_mp_MsgList_lh_TailPred 120
#define M68K_Process_pr_MsgPort_mp_MsgList_lh_Type 124
#define M68K_Process_pr_MsgPort_mp_MsgList_l_pad 125
#define M68K_Process_pr_MsgPort_mp_Pad_slock 126
#define M68K_Process_pr_MsgPort_mp_Pad_s_Owner 130
#define M68K_Process_pr_Pad 134
#define M68K_Process_pr_SegList 136
#define M68K_Process_pr_StackSize 140
#define M68K_Process_pr_GlobVec 144
#define M68K_Process_pr_TaskNum 148
#define M68K_Process_pr_StackBase 152
#define M68K_Process_pr_Result2 156
#define M68K_Process_pr_CurrentDir 160
#define M68K_Process_pr_CIS 164
#define M68K_Process_pr_COS 168
#define M68K_Process_pr_ConsoleTask 172
#define M68K_Process_pr_FileSystemTask 176
#define M68K_Process_pr_CLI 180
#define M68K_Process_pr_ReturnAddr 184
#define M68K_Process_pr_PktWait 188
#define M68K_Process_pr_WindowPtr 192
#define M68K_Process_pr_HomeDir 196
#define M68K_Process_pr_Flags 200
#define M68K_Process_pr_ExitCode 204
#define M68K_Process_pr_ExitData 208
#define M68K_Process_pr_Arguments 212
#define M68K_Process_pr_LocalVars_mlh_Head 216
#define M68K_Process_pr_LocalVars_mlh_Tail 220
#define M68K_Process_pr_LocalVars_mlh_TailPred 224
#define M68K_Process_pr_ShellPrivate 228
#define M68K_Process_pr_CES 232

/* struct IORequest: 32 bytes on m68k (IORequest) */
#define M68K_IORequest_SIZEOF 32
#define M68K_IORequest_io_Message_mn_Node_ln_Succ 0
#define M68K_IORequest_io_Message_mn_Node_ln_Pred 4
#define M68K_IORequest_io_Message_mn_Node_ln_Type 8
#define M68K_IORequest_io_Message_mn_Node_ln_Pri 9
#define M68K_IORequest_io_Message_mn_Node_ln_Name 10
#define M68K_IORequest_io_Message_mn_ReplyPort 14
#define M68K_IORequest_io_Message_mn_Length 18
#define M68K_IORequest_io_Device 20
#define M68K_IORequest_io_Unit 24
#define M68K_IORequest_io_Command 28
#define M68K_IORequest_io_Flags 30
#define M68K_IORequest_io_Error 31

/* struct SemaphoreMessage: 24 bytes on m68k (SemaphoreMessage) */
#define M68K_SemaphoreMessage_SIZEOF 24
#define M68K_SemaphoreMessage_ssm_Message_mn_Node_ln_Succ 0
#define M68K_SemaphoreMessage_ssm_Message_mn_Node_ln_Pred 4
#define M68K_SemaphoreMessage_ssm_Message_mn_Node_ln_Type 8
#define M68K_SemaphoreMessage_ssm_Message_mn_Node_ln_Pri 9
#define M68K_SemaphoreMessage_ssm_Message_mn_Node_ln_Name 10
#define M68K_SemaphoreMessage_ssm_Message_mn_ReplyPort 14
#define M68K_SemaphoreMessage_ssm_Message_mn_Length 18
#define M68K_SemaphoreMessage_ssm_Semaphore 20

/* struct MemHeader: 32 bytes on m68k (MemHeader) */
#define M68K_MemHeader_SIZEOF 32
#define M68K_MemHeader_mh_Node_ln_Succ 0
#define M68K_MemHeader_mh_Node_ln_Pred 4
#define M68K_MemHeader_mh_Node_ln_Type 8
#define M68K_MemHeader_mh_Node_ln_Pri 9
#define M68K_MemHeader_mh_Node_ln_Name 10
#define M68K_MemHeader_mh_Attributes 14
#define M68K_MemHeader_mh_First 16
#define M68K_MemHeader_mh_Lower 20
#define M68K_MemHeader_mh_Upper 24
#define M68K_MemHeader_mh_Free 28

/* struct MemChunk: 8 bytes on m68k (MemChunk) */
#define M68K_MemChunk_SIZEOF 8
#define M68K_MemChunk_mc_Next 0
#define M68K_MemChunk_mc_Bytes 4

/* struct Interrupt: 22 bytes on m68k (Interrupt) */
#define M68K_Interrupt_SIZEOF 22
#define M68K_Interrupt_is_Node_ln_Succ 0
#define M68K_Interrupt_is_Node_ln_Pred 4
#define M68K_Interrupt_is_Node_ln_Type 8
#define M68K_Interrupt_is_Node_ln_Pri 9
#define M68K_Interrupt_is_Node_ln_Name 10
#define M68K_Interrupt_is_Data 14
#define M68K_Interrupt_is_Code 18

/* struct Hook: 20 bytes on m68k (Hook) */
#define M68K_Hook_SIZEOF 20
#define M68K_Hook_h_MinNode_mln_Succ 0
#define M68K_Hook_h_MinNode_mln_Pred 4
#define M68K_Hook_h_Entry 8
#define M68K_Hook_h_SubEntry 12
#define M68K_Hook_h_Data 16

/* struct Window: 156 bytes on m68k (Window) */
#define M68K_Window_SIZEOF 156
#define M68K_Window_NextWindow 0
#define M68K_Window_LeftEdge 4
#define M68K_Window_TopEdge 6
#define M68K_Window_Width 8
#define M68K_Window_Height 10
#define M68K_Window_MouseY 12
#define M68K_Window_MouseX 14
#define M68K_Window_MinWidth 16
#define M68K_Window_MinHeight 18
#define M68K_Window_MaxWidth 20
#define M68K_Window_MaxHeight 22
#define M68K_Window_Flags 24
#define M68K_Window_MenuStrip 28
#define M68K_Window_Title 32
#define M68K_Window_FirstRequest 36
#define M68K_Window_DMRequest 40
#define M68K_Window_ReqCount 44
#define M68K_Window_WScreen 46
#define M68K_Window_RPort 50
#define M68K_Window_BorderLeft 54
#define M68K_Window_BorderTop 55
#define M68K_Window_BorderRight 56
#define M68K_Window_BorderBottom 57
#define M68K_Window_BorderRPort 58
#define M68K_Window_FirstGadget 62
#define M68K_Window_Parent 66
#define M68K_Window_Descendant 70
#define M68K_Window_Pointer 74
#define M68K_Window_PtrHeight 78
#define M68K_Window_PtrWidth 79
#define M68K_Window_XOffset 80
#define M68K_Window_YOffset 81
#define M68K_Window_IDCMPFlags 82
#define M68K_Window_UserPort 86
#define M68K_Window_WindowPort 90
#define M68K_Window_MessageKey 94
#define M68K_Window_DetailPen 98
#define M68K_Window_BlockPen 99
#define M68K_Window_CheckMark 100
#define M68K_Window_ScreenTitle 104
#define M68K_Window_GZZMouseX 108
#define M68K_Window_GZZMouseY 110
#define M68K_Window_GZZWidth 112
#define M68K_Window_GZZHeight 114
#define M68K_Window_ExtData 116
#define M68K_Window_UserData 120
#define M68K_Window_WLayer 124
#define M68K_Window_IFont 128
#define M68K_Window_MoreFlags 132
#define M68K_Window_RelLeftEdge 136
#define M68K_Window_RelTopEdge 138
#define M68K_Window_firstchild 140
#define M68K_Window_prevchild 144
#define M68K_Window_nextchild 148
#define M68K_Window_parent 152

/* struct IntuiMessage: 52 bytes on m68k (IntuiMessage) */
#define M68K_IntuiMessage_SIZEOF 52
#define M68K_IntuiMessage_ExecMessage_mn_Node_ln_Succ 0
#define M68K_IntuiMessage_ExecMessage_mn_Node_ln_Pred 4
#define M68K_IntuiMessage_ExecMessage_mn_Node_ln_Type 8
#define M68K_IntuiMessage_ExecMessage_mn_Node_ln_Pri 9
#define M68K_IntuiMessage_ExecMessage_mn_Node_ln_Name 10
#define M68K_IntuiMessage_ExecMessage_mn_ReplyPort 14
#define M68K_IntuiMessage_ExecMessage_mn_Length 18
#define M68K_IntuiMessage_Class 20
#define M68K_IntuiMessage_Code 24
#define M68K_IntuiMessage_Qualifier 26
#define M68K_IntuiMessage_IAddress 28
#define M68K_IntuiMessage_MouseX 32
#define M68K_IntuiMessage_MouseY 34
#define M68K_IntuiMessage_Seconds 36
#define M68K_IntuiMessage_Micros 40
#define M68K_IntuiMessage_IDCMPWindow 44
#define M68K_IntuiMessage_SpecialLink 48

/* struct ClockData: 14 bytes on m68k (ClockData) */
#define M68K_ClockData_SIZEOF 14
#define M68K_ClockData_sec 0
#define M68K_ClockData_min 2
#define M68K_ClockData_hour 4
#define M68K_ClockData_mday 6
#define M68K_ClockData_month 8
#define M68K_ClockData_year 10
#define M68K_ClockData_wday 12

/* struct NewWindow: 48 bytes on m68k (NewWindow) */
#define M68K_NewWindow_SIZEOF 48
#define M68K_NewWindow_LeftEdge 0
#define M68K_NewWindow_TopEdge 2
#define M68K_NewWindow_Width 4
#define M68K_NewWindow_Height 6
#define M68K_NewWindow_DetailPen 8
#define M68K_NewWindow_BlockPen 9
#define M68K_NewWindow_IDCMPFlags 10
#define M68K_NewWindow_Flags 14
#define M68K_NewWindow_FirstGadget 18
#define M68K_NewWindow_CheckMark 22
#define M68K_NewWindow_Title 26
#define M68K_NewWindow_Screen 30
#define M68K_NewWindow_BitMap 34
#define M68K_NewWindow_MinWidth 38
#define M68K_NewWindow_MinHeight 40
#define M68K_NewWindow_MaxWidth 42
#define M68K_NewWindow_MaxHeight 44
#define M68K_NewWindow_Type 46

/* struct NewScreen: 32 bytes on m68k (NewScreen) */
#define M68K_NewScreen_SIZEOF 32
#define M68K_NewScreen_LeftEdge 0
#define M68K_NewScreen_TopEdge 2
#define M68K_NewScreen_Width 4
#define M68K_NewScreen_Height 6
#define M68K_NewScreen_Depth 8
#define M68K_NewScreen_DetailPen 10
#define M68K_NewScreen_BlockPen 11
#define M68K_NewScreen_ViewModes 12
#define M68K_NewScreen_Type 14
#define M68K_NewScreen_Font 16
#define M68K_NewScreen_DefaultTitle 20
#define M68K_NewScreen_Gadgets 24
#define M68K_NewScreen_CustomBitMap 28

/* struct EasyStruct: 20 bytes on m68k (EasyStruct) */
#define M68K_EasyStruct_SIZEOF 20
#define M68K_EasyStruct_es_StructSize 0
#define M68K_EasyStruct_es_Flags 4
#define M68K_EasyStruct_es_Title 8
#define M68K_EasyStruct_es_TextFormat 12
#define M68K_EasyStruct_es_GadgetFormat 16

/* struct Remember: 12 bytes on m68k (Remember) */
#define M68K_Remember_SIZEOF 12
#define M68K_Remember_NextRemember 0
#define M68K_Remember_RememberSize 4
#define M68K_Remember_Memory 8

/* struct CSource: 12 bytes on m68k (CSource) */
#define M68K_CSource_SIZEOF 12
#define M68K_CSource_CS_Buffer 0
#define M68K_CSource_CS_Length 4
#define M68K_CSource_CS_CurChr 8

/* struct DosPacket: 48 bytes on m68k (DosPacket) */
#define M68K_DosPacket_SIZEOF 48
#define M68K_DosPacket_dp_Link 0
#define M68K_DosPacket_dp_Port 4
#define M68K_DosPacket_dp_Type 8
#define M68K_DosPacket_dp_Res1 12
#define M68K_DosPacket_dp_Res2 16
#define M68K_DosPacket_dp_Arg1 20
#define M68K_DosPacket_dp_Arg2 24
#define M68K_DosPacket_dp_Arg3 28
#define M68K_DosPacket_dp_Arg4 32
#define M68K_DosPacket_dp_Arg5 36
#define M68K_DosPacket_dp_Arg6 40
#define M68K_DosPacket_dp_Arg7 44

/* struct LocalVar: 24 bytes on m68k (LocalVar) */
#define M68K_LocalVar_SIZEOF 24
#define M68K_LocalVar_lv_Node_ln_Succ 0
#define M68K_LocalVar_lv_Node_ln_Pred 4
#define M68K_LocalVar_lv_Node_ln_Type 8
#define M68K_LocalVar_lv_Node_ln_Pri 9
#define M68K_LocalVar_lv_Node_ln_Name 10
#define M68K_LocalVar_lv_Flags 14
#define M68K_LocalVar_lv_Value 16
#define M68K_LocalVar_lv_Len 20

/* struct ExAllControl: 16 bytes on m68k (ExAllControl) */
#define M68K_ExAllControl_SIZEOF 16
#define M68K_ExAllControl_eac_Entries 0
#define M68K_ExAllControl_eac_LastKey 4
#define M68K_ExAllControl_eac_MatchString 8
#define M68K_ExAllControl_eac_MatchFunc 12

/* struct FileInfoBlock: 260 bytes on m68k (FileInfoBlock32) */
#define M68K_FileInfoBlock_SIZEOF 260
#define M68K_FileInfoBlock_fib_DiskKey 0
#define M68K_FileInfoBlock_fib_DirEntryType 4
#define M68K_FileInfoBlock_fib_FileName 8
#define M68K_FileInfoBlock_fib_Protection 116
#define M68K_FileInfoBlock_fib_EntryType 120
#define M68K_FileInfoBlock_fib_Size 124
#define M68K_FileInfoBlock_fib_NumBlocks 128
#define M68K_FileInfoBlock_fib_Date_ds_Days 132
#define M68K_FileInfoBlock_fib_Date_ds_Minute 136
#define M68K_FileInfoBlock_fib_Date_ds_Tick 140
#define M68K_FileInfoBlock_fib_Comment 144
#define M68K_FileInfoBlock_fib_OwnerUID 224
#define M68K_FileInfoBlock_fib_OwnerGID 226
#define M68K_FileInfoBlock_fib_Reserved 228

/* struct ExAllData: 40 bytes on m68k (ExAllData32) */
#define M68K_ExAllData_SIZEOF 40
#define M68K_ExAllData_ed_Next 0
#define M68K_ExAllData_ed_Name 4
#define M68K_ExAllData_ed_Type 8
#define M68K_ExAllData_ed_Size 12
#define M68K_ExAllData_ed_Prot 16
#define M68K_ExAllData_ed_Days 20
#define M68K_ExAllData_ed_Mins 24
#define M68K_ExAllData_ed_Ticks 28
#define M68K_ExAllData_ed_Comment 32
#define M68K_ExAllData_ed_OwnerUID 36
#define M68K_ExAllData_ed_OwnerGID 38

/* struct GelsInfo: 38 bytes on m68k (GelsInfo) */
#define M68K_GelsInfo_SIZEOF 38
#define M68K_GelsInfo_sprRsrvd 0
#define M68K_GelsInfo_Flags 1
#define M68K_GelsInfo_gelHead 2
#define M68K_GelsInfo_gelTail 6
#define M68K_GelsInfo_nextLine 10
#define M68K_GelsInfo_lastColor 14
#define M68K_GelsInfo_collHandler 18
#define M68K_GelsInfo_leftmost 22
#define M68K_GelsInfo_rightmost 24
#define M68K_GelsInfo_topmost 26
#define M68K_GelsInfo_bottommost 28
#define M68K_GelsInfo_firstBlissObj 30
#define M68K_GelsInfo_lastBlissObj 34

/* struct collTable: 64 bytes on m68k (collTable) */
#define M68K_collTable_SIZEOF 64
#define M68K_collTable_collPtrs 0

/* struct AnimOb: 42 bytes on m68k (AnimOb) */
#define M68K_AnimOb_SIZEOF 42
#define M68K_AnimOb_NextOb 0
#define M68K_AnimOb_PrevOb 4
#define M68K_AnimOb_Clock 8
#define M68K_AnimOb_AnOldY 12
#define M68K_AnimOb_AnOldX 14
#define M68K_AnimOb_AnY 16
#define M68K_AnimOb_AnX 18
#define M68K_AnimOb_YVel 20
#define M68K_AnimOb_XVel 22
#define M68K_AnimOb_YAccel 24
#define M68K_AnimOb_XAccel 26
#define M68K_AnimOb_RingYTrans 28
#define M68K_AnimOb_RingXTrans 30
#define M68K_AnimOb_AnimORoutine 32
#define M68K_AnimOb_HeadComp 36
#define M68K_AnimOb_AUserExt 40

/* struct AnimComp: 38 bytes on m68k (AnimComp) */
#define M68K_AnimComp_SIZEOF 38
#define M68K_AnimComp_Flags 0
#define M68K_AnimComp_Timer 2
#define M68K_AnimComp_TimeSet 4
#define M68K_AnimComp_NextComp 6
#define M68K_AnimComp_PrevComp 10
#define M68K_AnimComp_NextSeq 14
#define M68K_AnimComp_PrevSeq 18
#define M68K_AnimComp_AnimCRoutine 22
#define M68K_AnimComp_YTrans 26
#define M68K_AnimComp_XTrans 28
#define M68K_AnimComp_HeadOb 30
#define M68K_AnimComp_AnimBob 34

/* struct Bob: 32 bytes on m68k (Bob) */
#define M68K_Bob_SIZEOF 32
#define M68K_Bob_Flags 0
#define M68K_Bob_SaveBuffer 2
#define M68K_Bob_ImageShadow 6
#define M68K_Bob_Before 10
#define M68K_Bob_After 14
#define M68K_Bob_BobVSprite 18
#define M68K_Bob_BobComp 22
#define M68K_Bob_DBuffer 26
#define M68K_Bob_BUserExt 30

/* struct VSprite: 60 bytes on m68k (VSprite) */
#define M68K_VSprite_SIZEOF 60
#define M68K_VSprite_NextVSprite 0
#define M68K_VSprite_PrevVSprite 4
#define M68K_VSprite_IntVSprite 8
#define M68K_VSprite_ClearPath 12
#define M68K_VSprite_OldY 16
#define M68K_VSprite_OldX 18
#define M68K_VSprite_Flags 20
#define M68K_VSprite_Y 22
#define M68K_VSprite_X 24
#define M68K_VSprite_Height 26
#define M68K_VSprite_Width 28
#define M68K_VSprite_Depth 30
#define M68K_VSprite_MeMask 32
#define M68K_VSprite_HitMask 34
#define M68K_VSprite_ImageData 36
#define M68K_VSprite_BorderLine 40
#define M68K_VSprite_CollMask 44
#define M68K_VSprite_SprColors 48
#define M68K_VSprite_VSBob 52
#define M68K_VSprite_PlanePick 56
#define M68K_VSprite_PlaneOnOff 57
#define M68K_VSprite_VUserExt 58

/* struct UCopList: 12 bytes on m68k (UCopList) */
#define M68K_UCopList_SIZEOF 12
#define M68K_UCopList_Next 0
#define M68K_UCopList_FirstCopList 4
#define M68K_UCopList_CopList 8

/* struct CopList: 38 bytes on m68k (CopList) */
#define M68K_CopList_SIZEOF 38
#define M68K_CopList_Next 0
#define M68K_CopList__CopList 4
#define M68K_CopList__ViewPort 8
#define M68K_CopList_CopIns 12
#define M68K_CopList_CopPtr 16
#define M68K_CopList_CopLStart 20
#define M68K_CopList_CopSStart 24
#define M68K_CopList_Count 28
#define M68K_CopList_MaxCount 30
#define M68K_CopList_DyOffset 32
#define M68K_CopList_SLRepeat 34
#define M68K_CopList_Flags 36

/* struct CopIns: 6 bytes on m68k (CopIns) */
#define M68K_CopIns_SIZEOF 6
#define M68K_CopIns_OpCode 0
#define M68K_CopIns_u3_nxtlist 2

/* struct SimpleSprite: 12 bytes on m68k (SimpleSprite) */
#define M68K_SimpleSprite_SIZEOF 12
#define M68K_SimpleSprite_posctldata 0
#define M68K_SimpleSprite_height 4
#define M68K_SimpleSprite_x 6
#define M68K_SimpleSprite_y 8
#define M68K_SimpleSprite_num 10

/* struct Rectangle: 8 bytes on m68k (Rectangle) */
#define M68K_Rectangle_SIZEOF 8
#define M68K_Rectangle_MinX 0
#define M68K_Rectangle_MinY 2
#define M68K_Rectangle_MaxX 4
#define M68K_Rectangle_MaxY 6

/* struct CyberModeNode: 60 bytes on m68k (CyberModeNode) */
#define M68K_CyberModeNode_SIZEOF 60
#define M68K_CyberModeNode_Node_ln_Succ 0
#define M68K_CyberModeNode_Node_ln_Pred 4
#define M68K_CyberModeNode_Node_ln_Type 8
#define M68K_CyberModeNode_Node_ln_Pri 9
#define M68K_CyberModeNode_Node_ln_Name 10
#define M68K_CyberModeNode_ModeText 14
#define M68K_CyberModeNode_DisplayID 46
#define M68K_CyberModeNode_Width 50
#define M68K_CyberModeNode_Height 52
#define M68K_CyberModeNode_Depth 54
#define M68K_CyberModeNode_DisplayTagList 56

/* struct CDrawMsg: 26 bytes on m68k (CDrawMsg) */
#define M68K_CDrawMsg_SIZEOF 26
#define M68K_CDrawMsg_cdm_MemPtr 0
#define M68K_CDrawMsg_cdm_offx 4
#define M68K_CDrawMsg_cdm_offy 8
#define M68K_CDrawMsg_cdm_xsize 12
#define M68K_CDrawMsg_cdm_ysize 16
#define M68K_CDrawMsg_cdm_BytesPerRow 20
#define M68K_CDrawMsg_cdm_BytesPerPix 22
#define M68K_CDrawMsg_cdm_ColorModel 24

/* struct AreaInfo: 24 bytes on m68k (AreaInfo) */
#define M68K_AreaInfo_SIZEOF 24
#define M68K_AreaInfo_VctrTbl 0
#define M68K_AreaInfo_VctrPtr 4
#define M68K_AreaInfo_FlagTbl 8
#define M68K_AreaInfo_FlagPtr 12
#define M68K_AreaInfo_Count 16
#define M68K_AreaInfo_MaxCount 18
#define M68K_AreaInfo_FirstX 20
#define M68K_AreaInfo_FirstY 22

/* struct TmpRas: 8 bytes on m68k (TmpRas) */
#define M68K_TmpRas_SIZEOF 8
#define M68K_TmpRas_RasPtr 0
#define M68K_TmpRas_Size 4

#endif /* EMU68K_GUEST_OFFSETS_H */
