/* GENERATED by graft/gen-emu68k-bridge - do not edit.
 *
 * The libraries the bridge has generated crossings for, and
 * therefore the ones the guest is given a native base for.
 */

#ifndef EMU68K_GENLIBS_H
#define EMU68K_GENLIBS_H

#define EMU68K_SERVABLE_LIBS(X) \
    X("exec.library") \
    X("dos.library") \
    X("utility.library") \
    X("intuition.library") \
    X("graphics.library") \
    X("layers.library") \
    X("gadtools.library") \
    X("asl.library") \
    X("icon.library") \
    X("iffparse.library") \
    X("commodities.library") \
    X("diskfont.library") \
    X("locale.library") \
    X("keymap.library") \
    X("datatypes.library") \
    X("expansion.library") \
    X("cybergraphics.library") \
    X("mathffp.library") \
    X("mathieeesingbas.library") \
    X("mathieeedoubbas.library") \
    X("mathieeesingtrans.library") \
    X("mathieeedoubtrans.library") \
    X("mathtrans.library") \
    X("workbench.library") \
    /* end */

#endif /* EMU68K_GENLIBS_H */
