/* GENERATED by graft/gen-struct-layouts - do not edit.
 *
 * m68k (AmigaOS ABI) offsets of the structures the 68k execution
 * service fills in on the guest's behalf. Derived from the AROS
 * headers with a 2-byte-packed m68k probe and locked by the
 * generator's KNOWN_M68K self-check. */
#ifndef EMU68K_GUEST_OFFSETS_H
#define EMU68K_GUEST_OFFSETS_H

/* struct Task: 92 bytes on m68k (Task) */
#define M68K_Task_SIZEOF 92
#define M68K_Task_tc_Node_ln_Succ 0
#define M68K_Task_tc_Node_ln_Pred 4
#define M68K_Task_tc_Node_ln_Type 8
#define M68K_Task_tc_Node_ln_Pri 9
#define M68K_Task_tc_Node_ln_Name 10
#define M68K_Task_tc_Flags 14
#define M68K_Task_tc_State 15
#define M68K_Task_tc_IDNestCnt 16
#define M68K_Task_tc_TDNestCnt 17
#define M68K_Task_tc_SigAlloc 18
#define M68K_Task_tc_SigWait 22
#define M68K_Task_tc_SigRecvd 26
#define M68K_Task_tc_SigExcept 30
#define M68K_Task_tc_UnionETask_tc_ETrap_tc_ETrapAlloc 34
#define M68K_Task_tc_UnionETask_tc_ETrap_tc_ETrapAble 36
#define M68K_Task_tc_ExceptData 38
#define M68K_Task_tc_ExceptCode 42
#define M68K_Task_tc_TrapData 46
#define M68K_Task_tc_TrapCode 50
#define M68K_Task_tc_SPReg 54
#define M68K_Task_tc_SPLower 58
#define M68K_Task_tc_SPUpper 62
#define M68K_Task_tc_Switch 66
#define M68K_Task_tc_Launch 70
#define M68K_Task_tc_MemEntry_lh_Head 74
#define M68K_Task_tc_MemEntry_lh_Tail 78
#define M68K_Task_tc_MemEntry_lh_TailPred 82
#define M68K_Task_tc_MemEntry_lh_Type 86
#define M68K_Task_tc_MemEntry_l_pad 87
#define M68K_Task_tc_UserData 88

/* struct ExecBase: 640 bytes on m68k (ExecBase) */
#define M68K_ExecBase_SIZEOF 640
#define M68K_ExecBase_LibNode_lib_Node_ln_Succ 0
#define M68K_ExecBase_LibNode_lib_Node_ln_Pred 4
#define M68K_ExecBase_LibNode_lib_Node_ln_Type 8
#define M68K_ExecBase_LibNode_lib_Node_ln_Pri 9
#define M68K_ExecBase_LibNode_lib_Node_ln_Name 10
#define M68K_ExecBase_LibNode_lib_Flags 14
#define M68K_ExecBase_LibNode_lib_pad 15
#define M68K_ExecBase_LibNode_lib_NegSize 16
#define M68K_ExecBase_LibNode_lib_PosSize 18
#define M68K_ExecBase_LibNode_lib_Version 20
#define M68K_ExecBase_LibNode_lib_Revision 22
#define M68K_ExecBase_LibNode_lib_IdString 24
#define M68K_ExecBase_LibNode_lib_Sum 28
#define M68K_ExecBase_LibNode_lib_OpenCnt 32
#define M68K_ExecBase_SoftVer 34
#define M68K_ExecBase_LowMemChkSum 36
#define M68K_ExecBase_ChkBase 38
#define M68K_ExecBase_ColdCapture 42
#define M68K_ExecBase_CoolCapture 46
#define M68K_ExecBase_WarmCapture 50
#define M68K_ExecBase_SysStkUpper 54
#define M68K_ExecBase_SysStkLower 58
#define M68K_ExecBase_MaxLocMem 62
#define M68K_ExecBase_DebugEntry 66
#define M68K_ExecBase_DebugData 70
#define M68K_ExecBase_AlertData 74
#define M68K_ExecBase_MaxExtMem 78
#define M68K_ExecBase_ChkSum 82
#define M68K_ExecBase_IntVects 84
#define M68K_ExecBase_ThisTask 276
#define M68K_ExecBase_IdleCount 280
#define M68K_ExecBase_DispCount 284
#define M68K_ExecBase_Quantum 288
#define M68K_ExecBase_Elapsed 290
#define M68K_ExecBase_SysFlags 292
#define M68K_ExecBase_IDNestCnt 294
#define M68K_ExecBase_TDNestCnt 295
#define M68K_ExecBase_AttnFlags 296
#define M68K_ExecBase_AttnResched 298
#define M68K_ExecBase_ResModules 300
#define M68K_ExecBase_TaskTrapCode 304
#define M68K_ExecBase_TaskExceptCode 308
#define M68K_ExecBase_TaskExitCode 312
#define M68K_ExecBase_TaskSigAlloc 316
#define M68K_ExecBase_TaskTrapAlloc 320
#define M68K_ExecBase_MemList_lh_Head 322
#define M68K_ExecBase_MemList_lh_Tail 326
#define M68K_ExecBase_MemList_lh_TailPred 330
#define M68K_ExecBase_MemList_lh_Type 334
#define M68K_ExecBase_MemList_l_pad 335
#define M68K_ExecBase_ResourceList_lh_Head 336
#define M68K_ExecBase_ResourceList_lh_Tail 340
#define M68K_ExecBase_ResourceList_lh_TailPred 344
#define M68K_ExecBase_ResourceList_lh_Type 348
#define M68K_ExecBase_ResourceList_l_pad 349
#define M68K_ExecBase_DeviceList_lh_Head 350
#define M68K_ExecBase_DeviceList_lh_Tail 354
#define M68K_ExecBase_DeviceList_lh_TailPred 358
#define M68K_ExecBase_DeviceList_lh_Type 362
#define M68K_ExecBase_DeviceList_l_pad 363
#define M68K_ExecBase_IntrList_lh_Head 364
#define M68K_ExecBase_IntrList_lh_Tail 368
#define M68K_ExecBase_IntrList_lh_TailPred 372
#define M68K_ExecBase_IntrList_lh_Type 376
#define M68K_ExecBase_IntrList_l_pad 377
#define M68K_ExecBase_LibList_lh_Head 378
#define M68K_ExecBase_LibList_lh_Tail 382
#define M68K_ExecBase_LibList_lh_TailPred 386
#define M68K_ExecBase_LibList_lh_Type 390
#define M68K_ExecBase_LibList_l_pad 391
#define M68K_ExecBase_PortList_lh_Head 392
#define M68K_ExecBase_PortList_lh_Tail 396
#define M68K_ExecBase_PortList_lh_TailPred 400
#define M68K_ExecBase_PortList_lh_Type 404
#define M68K_ExecBase_PortList_l_pad 405
#define M68K_ExecBase_TaskReady_lh_Head 406
#define M68K_ExecBase_TaskReady_lh_Tail 410
#define M68K_ExecBase_TaskReady_lh_TailPred 414
#define M68K_ExecBase_TaskReady_lh_Type 418
#define M68K_ExecBase_TaskReady_l_pad 419
#define M68K_ExecBase_TaskWait_lh_Head 420
#define M68K_ExecBase_TaskWait_lh_Tail 424
#define M68K_ExecBase_TaskWait_lh_TailPred 428
#define M68K_ExecBase_TaskWait_lh_Type 432
#define M68K_ExecBase_TaskWait_l_pad 433
#define M68K_ExecBase_SoftInts 434
#define M68K_ExecBase_LastAlert 514
#define M68K_ExecBase_VBlankFrequency 530
#define M68K_ExecBase_PowerSupplyFrequency 531
#define M68K_ExecBase_SemaphoreList_lh_Head 532
#define M68K_ExecBase_SemaphoreList_lh_Tail 536
#define M68K_ExecBase_SemaphoreList_lh_TailPred 540
#define M68K_ExecBase_SemaphoreList_lh_Type 544
#define M68K_ExecBase_SemaphoreList_l_pad 545
#define M68K_ExecBase_KickMemPtr 546
#define M68K_ExecBase_KickTagPtr 550
#define M68K_ExecBase_KickCheckSum 554
#define M68K_ExecBase_ex_Pad0 558
#define M68K_ExecBase_ex_LaunchPoint 560
#define M68K_ExecBase_ex_RamLibPrivate 564
#define M68K_ExecBase_ex_EClockFrequency 568
#define M68K_ExecBase_ex_CacheControl 572
#define M68K_ExecBase_ex_TaskID 576
#define M68K_ExecBase_ex_Reserved1 580
#define M68K_ExecBase_ex_MMULock 600
#define M68K_ExecBase_ex_Reserved2 604
#define M68K_ExecBase_ex_DebugFlags 612
#define M68K_ExecBase_ex_MemHandlers_mlh_Head 616
#define M68K_ExecBase_ex_MemHandlers_mlh_Tail 620
#define M68K_ExecBase_ex_MemHandlers_mlh_TailPred 624
#define M68K_ExecBase_ex_MemHandler 628
#define M68K_ExecBase_DebugAROSBase 632
#define M68K_ExecBase_lb_TaskResBase 636

/* struct Library: 34 bytes on m68k (Library) */
#define M68K_Library_SIZEOF 34
#define M68K_Library_lib_Node_ln_Succ 0
#define M68K_Library_lib_Node_ln_Pred 4
#define M68K_Library_lib_Node_ln_Type 8
#define M68K_Library_lib_Node_ln_Pri 9
#define M68K_Library_lib_Node_ln_Name 10
#define M68K_Library_lib_Flags 14
#define M68K_Library_lib_pad 15
#define M68K_Library_lib_NegSize 16
#define M68K_Library_lib_PosSize 18
#define M68K_Library_lib_Version 20
#define M68K_Library_lib_Revision 22
#define M68K_Library_lib_IdString 24
#define M68K_Library_lib_Sum 28
#define M68K_Library_lib_OpenCnt 32

/* struct CommandLineInterface: 68 bytes on m68k (CommandLineInterface) */
#define M68K_CommandLineInterface_SIZEOF 68
#define M68K_CommandLineInterface_cli_Result2 0
#define M68K_CommandLineInterface_cli_SetName 4
#define M68K_CommandLineInterface_cli_CommandDir 8
#define M68K_CommandLineInterface_cli_ReturnCode 12
#define M68K_CommandLineInterface_cli_CommandName 16
#define M68K_CommandLineInterface_cli_FailLevel 20
#define M68K_CommandLineInterface_cli_Prompt 24
#define M68K_CommandLineInterface_cli_StandardInput 28
#define M68K_CommandLineInterface_cli_CurrentInput 32
#define M68K_CommandLineInterface_cli_CommandFile 36
#define M68K_CommandLineInterface_cli_Interactive 40
#define M68K_CommandLineInterface_cli_Background 44
#define M68K_CommandLineInterface_cli_CurrentOutput 48
#define M68K_CommandLineInterface_cli_DefaultStack 52
#define M68K_CommandLineInterface_cli_StandardOutput 56
#define M68K_CommandLineInterface_cli_Module 60
#define M68K_CommandLineInterface_cli_StandardError 64

/* struct MsgPort: 42 bytes on m68k (MsgPort) */
#define M68K_MsgPort_SIZEOF 42
#define M68K_MsgPort_mp_Node_ln_Succ 0
#define M68K_MsgPort_mp_Node_ln_Pred 4
#define M68K_MsgPort_mp_Node_ln_Type 8
#define M68K_MsgPort_mp_Node_ln_Pri 9
#define M68K_MsgPort_mp_Node_ln_Name 10
#define M68K_MsgPort_mp_Flags 14
#define M68K_MsgPort_mp_SigBit 15
#define M68K_MsgPort_mp_SigTask 16
#define M68K_MsgPort_mp_MsgList_lh_Head 20
#define M68K_MsgPort_mp_MsgList_lh_Tail 24
#define M68K_MsgPort_mp_MsgList_lh_TailPred 28
#define M68K_MsgPort_mp_MsgList_lh_Type 32
#define M68K_MsgPort_mp_MsgList_l_pad 33
#define M68K_MsgPort_mp_Pad_slock 34
#define M68K_MsgPort_mp_Pad_s_Owner 38

/* struct Message: 20 bytes on m68k (Message) */
#define M68K_Message_SIZEOF 20
#define M68K_Message_mn_Node_ln_Succ 0
#define M68K_Message_mn_Node_ln_Pred 4
#define M68K_Message_mn_Node_ln_Type 8
#define M68K_Message_mn_Node_ln_Pri 9
#define M68K_Message_mn_Node_ln_Name 10
#define M68K_Message_mn_ReplyPort 14
#define M68K_Message_mn_Length 18

/* struct List: 14 bytes on m68k (List) */
#define M68K_List_SIZEOF 14
#define M68K_List_lh_Head 0
#define M68K_List_lh_Tail 4
#define M68K_List_lh_TailPred 8
#define M68K_List_lh_Type 12
#define M68K_List_l_pad 13

/* struct Node: 14 bytes on m68k (Node) */
#define M68K_Node_SIZEOF 14
#define M68K_Node_ln_Succ 0
#define M68K_Node_ln_Pred 4
#define M68K_Node_ln_Type 8
#define M68K_Node_ln_Pri 9
#define M68K_Node_ln_Name 10

#endif /* EMU68K_GUEST_OFFSETS_H */
